kind: pipeline
name: default

steps:
- name: build
  image: alpine 
  environment:
    USERNAME:
      from_secret: username
  commands:
  - chmod +x test.sh
  - ./test.sh 

secrets:
  username:
    external:
      name: secret/data/docker#username
  password:
    external:
      name: secret/data/docker#password
