kind: pipeline
name: default

steps:
- name: build
  image: alpine 
  environment:
    USERNAME:
      from_secret: username
  commands:
  - echo test
  - echo $${USERNAME}

---
kind: secret

external_data:
  username:
    path: secret/data/docker
    name: username
  password:
    path: secret/data/docker
    name: password
