kind: pipeline
name: default

steps:
- name: build
  image: alpine 
  environment:
    USERNAME:
      from_secret: username
  commands:
  - chmod +x test.sh
  - ./test.sh 
  - echo $${USERNAME}
---
kind: secret

secrets:
  docker_username:
    external:
      name: secret/data/docker#username

  docker_password:
    external:
      name: secret/data/docker#password
